project:
  type: website
  output-dir: docs

website:
  title: "Eugen Pissarskoi"
  description: Ethik Nachhaltiger Entwicklung -- Argumentatanalyse
  page-navigation: true
  back-to-top-navigation: true
  favicon: ./graphics/EugenPissarskoi_kleiner_off.jpg
  twitter-card: true
  open-graph: true
  reader-mode: false
  navbar:  
    title: false
    logo: ./graphics/EugenPissarskoi_kleiner_off.jpg
    background: secondary
    left:
      - href: forschung.qmd
        text: Inhalte
      - href: wiss-aktivit.qmd
        text: Geschäftigkeit
      - href: lebenslauf.qmd
        text: Lebenslauf
    tools:
      - icon: envelope-at-fill
        href: mailto:mail@eugenpissarskoi.de
    tools-collapse: false
  page-footer:
    left: "Eugen Pissarskoi, 2024"
    center: 
      - text: "Impressum"
        href: about.qmd
      - text: "Datenschutz"
        href: datenschutz.qmd
  announcement: 
    icon: broadcast-pin
    dismissable: true
    content: aktuell -- [Podcast-Gespräch zu Klima und Wirtschaft](https://open.spotify.com/episode/2uepKONX6zxi8So8CyE9tr?si=2hzfSyXSQeGMKbZ1ao544Q)
    type: primary
    position: below-navbar
format:
  html:
    theme: 
      light: litera
      dark: cyborg
    css: styles.css
    toc: true
    hyphenate: true
    mainfont: sans-serif

execute:
  freeze: auto



