---
title: Forschungsinhalte
---
::: {.callout-note appearance="minimal" collapse="true"}
## Gesellschaftliche Wohlfahrt und Klimawandel

[Dieses Buch](https://www.oekom.de/buch/gesellschaftliche-wohlfahrt-und-kimawandel-9783865816856) legt die Grundlagen für meine Beschäftigung mit den Themen

* Handeln angesichts von [Ungewissheiten](#handeln-angesichts-von-ungewissheiten)
* Handeln angesichts von Uneinigkeit darüber, was [Gutes Leben](#vielfalt-von-vorstellungen-guten-lebens) ausmacht
* angemessene [Methoden](#methoden-wissenschaftlicher-politikberatung) für Rechtfertigung von Handlungsempfehlungen.

In diesem Buch **analysiere ich**, 

* wie Klimaökonom\*innen mit Hilfe von integrieten klima-ökonomischen Modellen (so genannte Integrated Assessment Models) mit der epistemischen und normativen Herausforderung umgehen. 

Darin **kritisiere ich**,

* dass die untersuchten klima-ökonomischen Modelle die bekannten Unsicherheiten nicht vollständig berücksichtigen
* dass die untersuchten klima-ökonomischen Modelle eine Theorie für die Bewertung von Konsequenzen von Klimastrategien unterstellen, gegen die sich zahlreiche normative Einwände vorbringen lassen (d.h. die Theorie widerspricht anderen, gut begründeten und breit akzeptierten normativen Thesen).

Ausgehend davon **konstruiere ich** ein Argument für ein Klimaziel,

  * das lediglich possibilistisches Zukunftswissen unterstellt und
  * Schutz der am meisten Benachteiligten als handlungsleitendes Prinzip für die Klimapolitik annimmt. 

:::

<!--
```{=html}
<div class="accordion" id="accordionExample">
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingOne">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
        Accordion Item #1</button>
    </h2>
    <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        <strong>This is the first item's accordion body.</strong> It is shown by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow.
      </div>
    </div>
  </div>
</div>
```
-->
# Intrinsisch motivierte Forschungsthemen
## Handeln angesichts von Ungewissheiten

```{=html}
<div class="accordion" id="accordionExample">
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingOne">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
        <strong>Pissarskoi (2014): Gesellschaftliche Wohlfahrt und Klimawandel, Kapitel 7</strong>
      </button>
    </h2>
    <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample" style="">
      <div class="accordion-body">
        In diesem Abschnitt entwickele ich ein Argument für ein Klimaziel, das lediglich possibilistische Vorhersagen über die Folgen des Klimawandels berücksichtigt.
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingTwo">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
        <strong>Pissarskoi (2018): The Controllability Precautionary Principle: Justiﬁcation of a Climate Policy Goal Under Uncertainty</strong>
      </button>
    </h2>
    <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample" style="">
      <div class="accordion-body">
        <ul>
        <li> Ich kritisiere zwei Argumente, die unter Anerkennung von Ungewissheiten über die Klimafolgen ein Klimaziel begründen. Mein Einwand richtet sich auf Varianten des Vorsorgeprinzips, die in den Argumenten unterstellt werden.</li>
        <li> Als Alternative dazu entwickele ich eine Variante des Vorsorgeprinzips -- das Kontrollierbarkeits-Vorsorgeprinzip, mit dem ein Klimaziel gerechtfertigt werden kann.</li>
       </ul>
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingThree">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
        <strong>Pissarskoi (unpublished): Possibly disastrous, but controllable – on dynamic decision making under uncertainty</strong>
      </button>
    </h2>
    <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        <ul>
         <li> Ich argumentiere, dass die bislang diskutierten Prinzipien für Entscheidungen unter Ungewissheit Ergebnis-abhängig (outcome-dependent) sind: sie leiten eine Handlungsempfehlung ausgehend vom Wert der möglichen Konsequenzen (Ergebnisse) der verfügbaren Entscheidungsoptionen ab.</li> 
          <ul> 
            <li><strong>Ergebnis-abhängige Entscheidungsprinzipien</strong> können allerings keine Entscheidung für ein Klimaziel begründen, da mögliche Konsequenzen der verfügbaren Handlungsoptionen nicht in eine Bewertungsrangfolge gebracht werden können.</li>
          </ul>
         <li>Als Alternative dazu schlage ich vor, Entscheidungen unter Ungewissheit mit Hilfe von <strong>Prozess-orientierten Entscheidungsprinzipien</strong> zu begründen.</li>
          <ul>
            <li>Ich erläutere die Grundstruktur von Prozess-orientierten Entscheidungsprinzipien</li>
            <li>Das Kontrollierbarkeits-Vorsorgeprinzip ist ein Beispiel für ein Prozess-orientiertes Entscheidungsprinzip. Ich schlage einen Weg zu dessen Operationalisierung vor.</li>
          </ul>
        </ul>
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingFour">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
        <strong>Kommentare zu gesellschaftlichen Kontroversen</strong>
      </button>
    </h2>
    <div id="collapseFour" class="accordion-collapse collapse" aria-labelledby="headingFour" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        In Blogbeiträgen habe ich gesellschaftliche Kontroversen kommentiert, die aus dem fehlenden Anerkennen der Ungewissheiten über die Folgen von anthropogenen Eingriffen in natürliche Systeme resultieren:
        <ul>
         <li> Im Beitrag <a href="https://www.praefaktisch.de/klimakrise/radikaler-versus-behutsamer-klimaschutz-warum-behutsamkeit-angesichts-der-risiken-ungerecht-waere/">"Radikaler verus behutsamer Klimaschutz"</a> kritisiere ich den Klimawissenschaftler Hans von Storch für seine in einem SPIEGEL-Interview geäußerte Kritik an Fridays for Future. Die eigentliche Kontroverse liegt in Uneinigkeit über richtiges Handeln angesichts von Ungewissheiten.</li> 
         <li>Im Beitrag <a href="https://www.praefaktisch.de/grenzen-des-wachstums/die-philosophisch-anspruchsvolle-hinterlassenschaft-des-berichtes-grenzen-des-wachstums/">"Die philosophisch anspruchsvolle Hinterlassenschaft des Berichts Grenzen des Wachstums"</a> argumentiere ich, dass der Bericht "Grenzen des Wachstums" die Menschheit mit dem Problem des Entscheidens angesichts von Ungewissheiten konfrontiert hat. Sowohl die Kritiker*innen des Berichts als auch seine Verteidiger*innen haben das jedoch übersehen.</li>
        </ul>
      </div>
    </div>
  </div>
</div>
```
<!--
### Kommentare zu gesellschaftlichen Kontroversen
In Blogbeiträgen habe ich gesellschaftliche Kontroversen kommentiert, die aus dem fehlenden Anerkennen der Ungewissheiten über die Folgen von anthropogenen Eingriffen in natürliche Systeme resultieren:

::: {.callout-note appearance="minimal" collapse="true"}
## 2020: Radikaler versus behutsamer Klimaschutz: warum Behutsamkeit angesichts der Risiken ungerecht wäre

  
In [diesem Blogbeitrag](https://www.praefaktisch.de/klimakrise/radikaler-versus-behutsamer-klimaschutz-warum-behutsamkeit-angesichts-der-risiken-ungerecht-waere/) kritisiere ich den Klimawissenschaftler Hans von Storch für seine in einem SPIEGEL-Interview geäußerte Kritik an Fridays for Future. Die eigentliche Kontroverse liegt in Uneinigkeit über richtiges Handeln angesichts von Ungewissheiten.
:::

::: {.callout-note appearance="minimal" collapse="true"}
## 2022: Die philosophisch anspruchsvolle Hinterlassenschaft des Berichtes „Grenzen des Wachstums“
  
In [diesem Blogbeitrag](https://www.praefaktisch.de/grenzen-des-wachstums/die-philosophisch-anspruchsvolle-hinterlassenschaft-des-berichtes-grenzen-des-wachstums/) argumentiere ich, dass der Bericht "Grenzen des Wachstums" die Menschheit mit dem Problem des Entscheidens angesichts von Ungewissheiten konfrontiert hat. Sowohl die Kritiker\*innen des Berichts als auch seine Verteidiger\*innen haben das jedoch übersehen. 
:::
-->

## Vorstellungen Guten Lebens

In einem früh industrialisierten und heute relativ wohlhabenden Land wie Deutschland resultiert ein gesellschaftspolitisches Hemmnis, Nachhaltigkeitspolitiken in Einklang mit den Forderungen intergenerationeller Gerechtigkeit zu realisieren, aus der Befürchtung, die Umsetzung dieser Politiken würde die Lebensqualität^[oder Wohlergehen oder Wohlstand oder soziale Wohlfahrt oder Gutes Leben] mindern. 

In den folgenden Publikationen habe mich mit den Fragen auseinandergesetzt:

* Ist diese Befürchtung berechtigt? 
* Falls sie berechtigt ist, was folgt daraus für die Ziele Nachhaltiger Entwicklung und Nachhaltigkeitspolitiken?
* Falls sie nicht berechtigt ist, mit welchen Argumenten können Mitmenschen davon überzeugt werden, dass sie keine Verluste der Lebensqualität befürchten sollten? 

::: {.callout-note appearance="minimal" collapse="true"}
### Pissarskoi (2014): Gesellschaftliche Wohlfahrt und Klimawandel, Kapitel 4 bis 6

Innerhalb der Wohlfahrtsökonomik werden politische Maßnahmen auf ihre Wirkungen auf gesamtgesellschaftliche Wohlfahrt bzw. gesamtgesellschaftliches Wohlergehen analysiert. Klimaökonom\*innen nutzen Theorien der Wohlfahrtsökonomik, um klimapolitische Strategien im Hinblick auf ihre Wohlfahrtswirkungen zu analysieren. 

Im Buch "Gesellschaftliche Wohlfahrt und Klimawandel":

* analysiere ich, welche Bedeutung von "Wohlfahrt" innerhalb der Wohlfahrtsökonomik unterstellt wird. Dabei untersuche ich, 
  * wie gesellschaftliche Wohlfahrt im ökonomischen Sinne mit verwandten normativen Begriffen wie "Lebensqualität", "Gutes Leben", das "Gute für die Gesellschaft" zusammenhängt.
  * ob es gute Gründe dafür gibt, die in der Ökonomik unterstellten Auffassungen gesellschaftlicher Wohlfahrt als politische Zielgröße aufzufassen. 

Ich argumentiere dafür, 

  * dass keine in der Ökonomik unterstellte Auffassung gesellschaftlicher Wohlfahrt alleiniges politisches Ziel darstellen sollte. 

In Kapitel 7 unterbreite ich den Vorschlag, klimapolitische Maßnahmen im Hinblick auf ihre Wirkung auf die am meisten Benachteiligten (anstatt im Hinblick auf ihre Wirkung auf gesellschaftliche Wohlfahrt) zu bewerten. 

  * Eine frühe Fassung dieses Kapitels ist [hier](https://www.metropolis-verlag.de/Klimagerechtigkeit/901/book.do) erschienen.

:::

::: {.callout-note appearance="minimal" collapse="true"}

### UBA-Berichte zur Relevanz der Debatten um Gutes Leben für die Nachhaltigkeitspolitik (2018)

Im Auftrag des Umweltbundesamtes haben wir analysiert, welche inhaltlichen Bezüge zwischen gesellschaftlichen Diskursen zum Thema "Gutes Leben" und der Nachhaltigkeitspolitik gibt.

* Der Bericht [Diskurse zum Guten Leben: Analyse ihrer Begriffe, ihrer Akteure und damit verbundener politischer Strategien](https://www.umweltbundesamt.de/publikationen/diskurse-guten-leben-analyse-ihrer-begriffe-ihrer) analysiert drei Diskurse, die um das Jahr 2015 in der Wissenschaft, Politik und unter zivilgesellschaftlichen Akteuren das Thema "Gutes Leben" zum Gegenstand hatten:
  * Beyond-GDP-Diskurs
  * Glück
  * Postwachstum

* Der Bericht [Was kann Nachhaltigkeitspolitik vom Guten Leben lernen?](https://www.umweltbundesamt.de/publikationen/was-kann-nachhaltigkeitspolitik-vom-guten-leben) 
  * analysiert inhaltliche Überschneidungen zwischen den Diskursen zum Guten Leben und den Zielen der Nachhaltigen Entwicklung. 
  * eruiert Überlegungen, ob und wie die politische Akzeptanz von  Nachhaltigkeitsbelangen durch Bezüge zu Diskursen Guten Lebens verbessert werden kann.
:::

::: {.callout-note appearance="minimal" collapse="true"}
### Pissarskoi and Singo (2024): Neglected Components in Dominant Accounts of a Good Life? — Disagreements among Maasai Pastoralists

[Dieser Text](https://link.springer.com/article/10.1007/s12115-024-00988-4) ist im Rahmen des Forschungsvorhabens [BATATA](https://batata-bioeconomy.de/) erstellt worden (s. auch das Themenfeld [Bioökonomie](#bioökonomie)). Darin

* spezifizieren wir zwei kontroverse Auffassungen Guten Lebens:
  * eine im Globalen Nprden weit verbreitete Auffassung 
  * eine aus der Kritik an der verbreiteten Auffassung abgeleitete Konzeption Guten Lebens. Die Kritik stammt von einigen zivilgesellschaftlichen Akteuren aus dem Globalen Norden sowie aus dem post-kolonialen Diskurs. 
* präsentieren Ergebnisse von Feldforschung unter semi-nomadisch lebenden Viehzüchtern in Tansania. Darin haben wir sie nach ihren Auffassungen Guten Lebens befragt.
  * Aus den geführten Interviews ergibt sich, dass unter Maasai-Viehzüchtern eine analoge Uneinigkeit über Vorstellungen Guten Lebens herrscht, wie wir sie im Globalen Norden extrahiert haben. 
* Wir argumentieren auf der Basis dieser Ergebnisse, dass die kontroversen Auffassungen Guten Lebens Eingang in politische Entscheidungsfindungsprozesse finden sollen. 

:::

::: {.callout-note appearance="minimal" collapse="true"}
### Pissarskoi (unpublished): Is Economic Growth Necessary for a Good Life? – How to Decide this Controversy

In [diesem Text](https://nextclouds.webo.hosting/s/BqsmbHzLxzZbwZq)

* argumentiere ich dafür, dass die Befürchtung, dass eine ambitionierte Reduktion von Ressourcennutzung und Treibhausgasemissionen zur Minderung der Lebensqualität führe, auf der Annahme basiert, dass Auffassungen dessen, was Gutes Leben ausmacht, nicht veränderbar sind. Ich halte es jedoch für adäquater, dass Auffassungen Guten Lebens subjektive Gewichtungen von Bestandteilen Guten Lebens enthalten. Diese Gewichtungen von Bestandteilen Guten Lebens können sich verändern: durch neue Erfahrungen, Gewöhnung, Änderung sozialer Praktiken können sich die Gewichte dessen, für wie wichtig wir einzelne Bestandteile Guten Lebens halten, verändern. 

* Wenn diese Diagnose stimmt, ändert sich die argumentative Struktur der Debatte darüber, ob Nachhaltigkeitspolitiken die Lebensqualität mindern:
  * Vielmehr geht es nun um die (empirisch zu entscheidende) Frage, ob und wie Nachhaltigkeitspolitiken unsere Wertschätzungen (i.e. Gewichtungen der Bestandteile Guten Lebens) verändern.

* Und es ergeben sich eine neue ethische Frage für die Begründung von Nachhaltigkeitspolitiken: 
  + Sollen wir die Möglichkeit zulassen, unsere Wertschätzungen zu transformieren?
  * Ich beschreibe, wie diese Frage beantwortet werden kann.
:::

::: {.callout-note appearance="minimal" collapse="true"}
### Kollektiv "Unleasing Fantasy for Transformation"
Wie sollte eine erstrebenswerte Welt aussehen? Meist geben wir negative Antworten auf diese Fragen, indem wir auflisten, welche Ungerechtigkeiten aus der bestehenden Welt beseitigt werden sollten. Positive Antworten -- Visionen einer erstrebenswerten Welt -- sind selten zu hören. 

Visionen sind uns aber aus einer Literaturgattung vertraut: Science Fiction. Dort sind es meist naturwissenschaftlich prinzipiell manipulierbare Eigenschaften, die den Gegenstand des Visionierens darstellen. Ursula K. Le Guin ist ein Beispiel eine Autorin, in deren möglichen Welten soziale Institutionen und implizite Normen -- Eigentumsverhältnisse, Geschlechterstereotypen etc. -- anders -- eben erstrebenswert -- gestaltet sind. 

Mit unserem Kollektiv -- das sind Andrea Vetter, Corinna Dengler, [Jana Gebauer](https://www.kaloikostopia.org), Kristina Utz, Matthias Fersterer und ich -- organisieren wir Gelegenheiten zum Visionieren, Spekulieren, Brainstormen über Gutes Leben. 
:::


## Methoden der gesellschaftspolitischen Beratung

In meinen Forschungsarbeiten begründe ich normative Behauptungen, also Aussagen darüber, welche Klimaziele gerecht bzw. erstrebenswert sind, welche Strategien gewählt werden sollen und welche nicht. 

* Mit welchen Methoden können normative Behauptungen begründet werden? 
* Welche Beitrag kann wissenschaftliche Forschung zur Begründung normativer Behauptungen -- wie Bewertungen oder Handlungsempfehlungen -- leisten? 
* Welchen Beitrag sollten kreative Methoden -- Design Thinking, Visionieren, fiktionales Erzählen -- dabei spielen?

Diese Fragen beschäftigen mich, seit ich in meinem Promotionsvorhaben mit der Aufgabe konfrontiert war, einen Beitrag dazu zu leiten, um zu begründen, welches Klimaziel die Menschheit verfolgen sollte. 

:::{.panel-tabset}

### Methoden aus der Ökonomik

Umwelt- und Klimaökonom\*innen verwenden computergestützte Modelle -- so genannte Integrierte Bewertungsmodelle (IAMs für Integrated Assessment Models), die Teile ökologischer Systeme (beispielsweise den Kreislauf der Treibhausgase) mit ökonomischen Systemen koppeln -- um zu analysieren, welche umweltpolitischen Szenarien zu welchen Wohlfahrtseffekten führen werden. 

Ergebnisse von ökonomischen Analysen von umweltpolitischen Szenarien werden dafür verwendet, um politische Handlungsempfehlungen auszusprechen. 

In meinen Arbeiten habe ich 

* rekonstruiert, wie mit Hilfe von computergestützten umweltökonomischen Modellen Handlungsempfehlungen begründet werden;
* Einwände dagegen vorgebracht, mit Hilfe von IAMs Handlungsempfehlungen zu begründen;
* Vorschläge unterbreitet, wie computergestützte Modelle dazu genutzt werden könnten, politische Handlungsempfehlungen zu begründen.

```{=html}
<div class="accordion" id="accordionExample">
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingOne">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
        <strong>Pissarskoi (2014): Gesellschaftliche Wohlfahrt und Klimawandel, Kapitel 3</strong>
      </button>
    </h2>
    <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample" style="">
      <div class="accordion-body">
        In diesem Kapitel 
        <ul>
          <li>mache ich epistemische und normative Annahmen explizit, die in klimaökonomischen Modellen (IAMs) unterstellt werden;</li>
          <li>rekonstruiere das Argument, mit dem Ergebnisse der IAMS dazu genutzt werden, politische Handlungsempfehlungen auszusprechen</li>
          <li>zeige auf, warum Ergebnisse der IAMs sich nicht dazu eignen, Handlungsempfehlugen zu begründen.</li>
        </ul>
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingTwo">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
        <strong>Pissarskoi (2016a): Die Bürde des Möglichen. Zum verantwortlichen Umgang mit Unsicherheiten in Energieszenarien</strong>
      </button>
    </h2>
    <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample" style="">
      <div class="accordion-body">
      In diesem Aufsatz
        <ul>
        <li>beschreibe ich, wie mit Hilfe von energieökonomischen Modellen ökonomische Konsequenzen von energiepolitischen Szenarien analysiert werden und in Policy Papers veröffentlicht werden.</li>
        <li> Ich kritisiere, dass die Veröffentlichungen in den Policy Papers zu Missverständnissen bezüglich der bestehenden Unsicherheiten über die analysierten Szenarien einladen. Wegen dieser Missverständnisse können ungerechtfertigte Handlungsempfehlungen geschlussfolgert werden. </li>
        <li> Ich unterbreite Vorschläge, wie öffentliche Kommunikation von energiepolitischen Szenarienanalyse in demokratischen Gesellschaften verbessert werden könnte.</li>
       </ul>
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingThree">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
        <strong>Pissarskoi (2016b): Integrated Assessment Models: Kompass in einem magnetisierten Umfeld?</strong>
      </button>
    </h2>
    <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        In <a href="https://doi.org/10.14512/OEW310439">diesem Aufsatz</a> 
        <ul>
         <li> fasse ich die Kritik zusammen, warum Ergebnisse von Integrierten Bewertungsmodellen keine Handlungsorientierung in der Klima- oder Umweltpolitik leisten sollen.</li> 
         <li>Ich unterbreite einen Vorschlag, wie die Modelle gestaltet werden sollten, damit sie einen Beitrag zur gesellschaftlichen Entscheidungsfindung in der Klima- und Umweltpolitik leisten können.</li>
        </ul>
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingFour">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFour" aria-expanded="false" aria-controls="collapseThree">
        <strong>Pissarskoi (2019): Was eine moderne Klimaökonomik berücksichtigen sollte</strong>
      </button>
    </h2>
    <div id="collapseFour" class="accordion-collapse collapse" aria-labelledby="headingFour" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        In <a href="https://makronom.de/economists-for-future-was-eine-moderne-klimaoekonomik-beruecksichtigen-sollte-33199">diesem Aufsatz</a> (<a href="https://www.exploring-economics.org/de/entdecken/moderne-klimaoekonomik/">frei zugängliche Version</a>)
        <ul>
         <li> bringe ich Einwände dagegen vor, klimapolitische Entscheidungen mit Hilfe der Theorie des Erwarteten Nutzens -- einer in der Ökonomik verbreiteten Theorie zur Entscheidungsfindung unter Unsicherheit -- zu begründen.</li> 
         <li>Ich unterbreite Vorschläge, welche Beiträge klimaökonom\*innen zur klimapolitischen Entscheidungsfindung leisten könnten.</li>
        </ul>
      </div>
    </div>
  </div>
</div>
```

### Methoden Praktischer Ethik

Gibt es Methoden aus der Philosophie -- bzw. ihrer Subdisziplin "Praktische Ethik", die sich dezidiert mit der Auseinandersetzung mit normativen Fragen in gesellschaftlichen Kontroversen beschäftigt -- mit denen Handlungsempfehlungen begründet werden können? 

```{=html}
<div class="accordion" id="accordionExample">
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingOne">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
        <strong>Pissarskoi (2014): Gesellschaftliche Wohlfahrt und Klimawandel, Kapitel 2</strong>
      </button>
    </h2>
    <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample" style="">
      <div class="accordion-body">
        In diesem Kapitel 
        <ul>
          <li> diskutiere ich mehrere Vorschläge dafür, mit welchen Methoden ein klimapolitisches Ziel begründet werden kann.</li>
        </ul>
        Ich spreche mich dafür aus, das in der philosophischen Literatur als "Überlegungsgleichgewicht" bekannte Methode mit einer Argumentanalyse zu kombinieren, um die Plausibilität der normativen Begründungen für ein Klimaziel transparent zu machen. Diese Methode wende ich in den folgenden Kapiteln des Buches an. 
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingTwo">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
        <strong>Pissarskoi (2018): Das Problem der epistemisch-evaluativen Abwägung bei Entscheidungen unter Unsicherheit</strong>
      </button>
    </h2>
    <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample" style="">
      <div class="accordion-body">
      In diesem Aufsatz erläutere ich eine Besonderheit von Begründungen von Entscheidungen unter Unsicherheit aufmerksam:
      <ul>
        <li>sie beinhalten ethisch-epistemische Abwägungen, nämlich Abwägungen zwischen dem epistemischen Status möglicher Konsequenzen von Handlungsoptionen auf der einen und dem moralischen Wert ihrer möglichen Konsequenzen auf der anderen Seite.</li>
      </ul>
      Anschließend mache ich auf eine Forschungslücke aufmerksam:
      <ul>
        <li> Es ist keine Theorie bekannt, die allgemein erklärt, wie zwischen dem epistemischen Status möglicher Konsequenzen und ihrem moralischen Wert abgewogen werden soll.</li>
      </ul>
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingFour">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFour" aria-expanded="false" aria-controls="collapseThree">
        <strong>Charlotte Unruh, Susanne Hahn, and Eugen Pissarskoi (2022): Philosophical methods and being public philosophers</strong>
      </button>
    </h2>
    <div id="collapseFour" class="accordion-collapse collapse" aria-labelledby="headingFour" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        In <a href="https://www.oxfordpublicphilosophy.com/blog/ppt-making-philosophy-t9km2">diesem Beitrag</a> stellen wir einen Zusammenhang zwischen 
        <ul>
         <li> Rollen, die Philosoph*innen in außer-akademischen Kontexten einnehmen können, auf der einen Seite</li> 
         <li>und Methoden, mit denen sie die den Rollen angemessenen Aussagen rechtfertigen können.</li>
        </ul>
      </div>
    </div>
  </div>
</div>
```

### Transdisziplinäre Methoden

Bei gesellschaftspolitischen Auseinandersetzungen um Auffassungen Guten Lebens bzw. um Werthaltungen gegenüber Alltagspraktiken^[beispielsweise:
    Welchen Einfluss hat vegane Ernährung auf die Lebensqualität?
    Wie wirkt ein Umstieg vom Auto auf Fahrrad und öffentliche Verkehsmittel auf die individuelle Lebensqualität?]

spielen nicht nur Argumente, sondern auch Erfahrungen der Alltagspraktiken, Vorstellungen von möglichen Praktiken, Gewohnheiten und gesellschaftlichen Kooperationsformen eine Rolle. 

Transdisziplinäre Forschungsmethoden bezwecken, Experimetierräume zu kreieren, in denen Menschen von außerhalb der Wissenschaft mögliche Praktiken ausprobieren, das Wünschenswerte imaginieren, Ideen und Vorstellungen entfalten und ausprobieren und idealerweise eine Wirkung hinterlassen. 

Im Rahmen des Kollektivs "Unleashing Fantasy" habe ich Visionieren-Workshops mitgestaltet. Dabei interessiert mich folgende Meta-Fragen zu unserem Vorgehen:

* Wie subjektiv sind Visionen? Bzw. sind sie interpersonell teilbar? Wenn andere Menschen diejenige Vision, die ich attraktiv finde, nicht für erstrebenswert halten, begeht dann eine*r von uns einen Irrtum? 

* Wie vollständig sollten Visionen sein, die den Zweck haben, gesellschaftliche Handlungsorientierung zu unterstützen?

* Wie weit dürfen sich Visionen vom Status quo abkoppeln, um relevant zu sein bzw. zur Handlungsorientierung beizutragen? Anders formuliert: wie durchgeknallt dürfen sie sein?
:::

# Gesellschaftspolitisch motivierte Themen

## Ziele und Strategien Nachhaltiger Entwicklung

:::{.panel-tabset}

### Visionen und Strategien: Green-Growth, Degrowth etc.

Wenn wir anerkennen, dass ein früh industrialisiertes und relativ wohlhabendes Land wie Deutschland seinen Ressourcenverbrauch und seine Treibhausgasemissionen drastisch reduzieren soll, stellt sich die Frage, auf welche Weise bzw. mit welcher Strategie das am besten erfolgen sollte. 

Seit der Mitte 2000er Jahre werden Visionen bzw. wirtschaftspolitische Strategien, die alle eine sozial-ökologische Transformation von früh industrialisierten Ländern anstreben, unter einer großen Vielfalt von Namen diskutiert: Green Growth, Green Economy, Circular Economy, Postwachstum, Degrowth, A-Growth etc. 

Ich habe mich zum einen daran beteiligt, diese Diskurse zu systematisieren (Diefenbacher et al. 2015). Zwischen 2011 und 2017 habe ich den Blog [Postwachstum](https://www.postwachstum.de/) redaktionell koordiniiert.

Im Rahmen des Forschungsvorhabens PoWaRes^[„Ansätze zur Ressourcenschonung im Kontext von Postwachstumskonzepten“, im Auftrag des Umweltbundesamtes, Forschungskennzahl 3715 311040] habe ich in Zusammenarbeit mit Projektpartnern 

* Argumente hinsichtlich von zwei einander widersprechenden wirtschaftspolitischen Strategien, Degrowth und Green-Growth, analysiert. Beide Strategien haben wir als nicht überzeugend rechtfertigbar kritisiert;
* auf der Grundlage dieser Kritik eine alternative Strategie entwickelt: die **Vorsorgeorientierte Postwachstumsposition** (Petschow et al. 2028, Petschow und Pissarskoi 2025)

```{=html}
<div class="accordion" id="accordionExample">
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingOne">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
        <strong>Diefenbacher et al. (2015): Konzepte gesellschaftlichen Wohlstands und ökologische Gerechtigkeit</strong>
      </button>
    </h2>
    <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample" style="">
      <div class="accordion-body">
        In Kapitel 7 <a href="https://www.umweltbundesamt.de/publikationen/konzepte-gesellschaftlichen-wohlstands-oekologische">dieses Berichts</a>
        <ul>
          <li>haben wir mehrere Vorschläge für eine Systematisierung von Visionen und Strategien für eine sozial-ökologische Transformation erarbeitet. Die von uns betrachteten Positionen wurden in den Jahren um 2010 herum in Deutschland öffentlich artikuliert.</li>
        </ul>
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingTwo">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
        <strong>Petschow et al. (2018): Gesellschaftliches Wohlergehen innerhalb planetarer Grenzen. Der Ansatz einer vorsorgeorientierten Postwachstumsposition</strong>
      </button>
    </h2>
    <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample" style="">
      <div class="accordion-body">
        In Kapitel 2 <a href="https://www.umweltbundesamt.de/publikationen/vorsorgeorientierte-postwachstumsposition">dieses Berichts</a>
        <ul>
          <li>werden die einander widersprechenden Festlegungen der beiden kontroversen Strategien explizit benannt;</li>
          <li>wird dafür argumentiert, dass die Festlegungen sowohl in den Green-Growth als auch Degrowth-Positionen nicht begründet sind -- die Entscheidung über die wirtschaftspolitische Strategie zur Erreichung der Ziele Nachhaltiger Entwicklung muss unter Ungewissheit gerechtifertigt werden;</li>
          <li>wird die Vorsorgeorientierte Postwachstumsposition als vernünftige Handlungsoption in der epistemischen Situation der ungewissheit verteidigt.</li>
        </ul>
        Ergebnisse dieser Studie sind darüber hinaus erschienen in:
        <ul>
          <li> <a href="https://www.umweltbundesamt.de/publikationen/social-well-being-within-planetary-boundaries-the">Englische Fassung des Berichts</a></li>
          <li> <a href="https://doi.org/10.14361/9783839451809-025">Zusammenfassung der Ergebnisse</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingThree">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
        <strong>Petschow und Pissarskoi (2025): Die Vorsorgeorientierte Postwachstumsposition: von einer Kultur des Wachstums zu einer Kultur der Nachhaltigkeit</strong>
      </button>
    </h2>
    <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample" style="">
      <div class="accordion-body">
        <ul>
        <li> Dieser Aufsatz aktualisiert die Argumente aus Petschow et al. (2018) im Lichte der aktuelleren Literatur zu Green-Growth und Degrowth-Strategien.</li>
        <li> Wir leiten die Vorsorgeorientierte Postwachstumsposition aus der Kritik an den Positionen Green-Growth und Degrowth, beschreiben eine Grundstruktur von politischen Maßnahmen, die sie fordert, und weisen auf ihre Lücken hin</li>
       </ul>
      </div>
    </div>
  </div>
</div>
```


### Bioökonomie
Den Begriff "Bioökonomie" nutzen insbesondere politische Institutionen des Globalen Nordens (z.B. [OECD](https://www.oecd.org/en/publications/the-bioeconomy-to-2030_9789264056886-en.html), [Europäische Kommission](https://knowledge4policy.ec.europa.eu/bioeconomy_en), [Bundesregierung](https://www.wissenschaftsjahr.de/2020-21/index.html)) für Visionen einer Wirtschaftsweise und ihre wirtschaftspolitische Strategien, bei der die nicht-erneuerbaren Rohstoffe durch erneuerbare (bio-basierte) Ressourcen ersetzt sind.
Realisierung einer Bioökonomie birgt ethische Konflikte: Auf der einen Seite liefert die Forderung nach intergenerationeller Gerechtigkeit einen Grund dafür, Nutzung nicht-erneuerbarer Rohstoffe zu mininimieren. Auf der anderen Seite benötigt eine Bioökonomie zusätzliche Biomasse, deren Erzeugung landwirtschaftliche Flächen braucht. Letztere sind bereits heute knapp, da Landflächen vielfältigen Bedarfen dienen. 

Im Rahmen des Forschungsprojekts [BATATA -- Whose Bioeconomy? Tracing Visions of Socio-ecological Transformation and their Ethical Deliberation in Tanzania](https://batata-bioeconomy.de/) haben wir Konflikte zwischen Interessen der Länder Globalen Nordens, in denen Visionen der Bioökonomie entwickelt und politisch vorangetrieben werden, und Interessen der Bewohner\*innen der Länder des Globalen Südens -- in unserem Fall Tansania in Ostafrika, deren landwirtschaftliche Flächen in eine globale Bioökonome eingebunden werden sollen. Wir haben untersucht:

* empirisch: welche Visionen einer nachhaltigen Landnutzung marginalisierte Gruppen in Tansania haben: semi-nomadisch lebende Viehzüchter und Kleinbäuerinnen. 
* ethisch: welche ethischen Konflikte diese Visionen mit sich bringen und welche Handlungsoptionen im Lichte dieser Konflikte sich rechtfertigten lassen.

In [Diesem Blogbeitrag](https://www.wissenschaftsjahr.de/2020-21/aktuelles-aus-der-biooekonomie/koepfe-des-wandels/kontroverse-ueber-gesellschaftliche-grundziele-noetig.html) ([dauerhafter Link](https://doi.org/10.57754/FDAT.p33f8-5wf74)) plädiere ich dafür, über die Ziele der Bioökonomie mit breiter gesellschaftlicher Beteiligung zu reflektieren. 

Gesamte Projektergebnisse sind über die [Projektwebseite](https://batata-bioeconomy.de/) sowie auf dem [Repositorium der Universität Tübingen](https://fdat.uni-tuebingen.de/communities/batata?q=&l=list&p=1&s=10&sort=newest) zugänglich.


::: {.callout-note appearance="minimal" collapse="true"}
### Pissarskoi et al. (2020): Which Bio_economy for what Kind of Future? Towards the Re-politicization of a Discourse from the Global North with Insights from Tanzania

[Dieser Aufsatz](https://doi.org/10.3224/peripherie.v40i3-4.03) zeigt die Breite von Optionen einer Bioökonomie in Abhängigkeit von Zielen dessen, was eine Ökonomie verfolgen soll. 

* Wir rekonstruieren ethische Hintergrundannahmen, die in bioökonomischen Politikstrategien enthalten sind
* Wir zeigen auf, dass diese ethischen Hintergrundannahmen kontrovers beurteilt werden können
* Wir kritisieren, dass in den Ländern des GLobalen Nordens, die Bioökonomie-Politik bereits betreiben, keine öffentliche Debatte über die ethischen Hintergrundannahmen von Bioökonomie-Strategien stattfindet;
* Wir zeigen auf, dass zu Bioökonomie-Politik analoge politische Prozesse in einem ostafrikanischen Land, Tansania, durchaus zu finden sind. 
  * Dort sind es allerdings explizit ethische Diskurse, die kontrovers geführt werden
    * Das veranschaulichen wir anhand von Einblicken in die Debatten zur Landnutzung und zu Nutzung von genetisch modifiziertem Saatgut.
:::

::: {.callout-note appearance="minimal" collapse="true"}
### Ouma et al. (2022): Beyond Productivity: Reimagining Futures of Agriculture and Bioeconomy

[Dieser Text](https://doi.org/10.57754/FDAT.r1y0c-a1291) ist ein Bericht über die von uns ausgerichteten [Workshop "Beyond Producitivity"](https://uni-tuebingen.de/en/214393). Der Workshop adressierte die Frage: 

* Wie soll das Ziel der Produktivitätssteigerung in einer nachhaltigen Landwirtschaft beurteilt werden?

Eine Kurzfassung des Berichts ist auf dem [Blog der Zeitschrift Review of African Political Economy](https://roape.net/2022/02/17/beyond-productivity-reimagining-futures-of-agriculture-and-bioeconomy/) erschienen.

:::

### Klimaschutzziele

Eine Herausforderung, ein globales Klimaschutzziel zu begründen, liegt darin, dass die Folgen des Klimawandels sowie die Kosten des Aufwandes für Klimaschutz nur unpräzise vorhergesagt werden können. Selbst wenn die Menschheit sich darauf einigt, ein bestimmtes Temperaturziel zu verfolgen -- wie das 1.5°C aus dem Pariser Abkommen in 2015 -- bleibt noch zu klären, wie hoch die Treibhausgaskonzentration in der Atmosphäre sein darf, um dieses Temperaturziel einzuhalten. 

In meinen Arbeiten habe ich dafür argumentiert, ein solches Klimaziel mit Hilfe von [Spezifikationen des Vorsorgeprinzips](#handeln-angesichts-von-ungewissheiten) -- ich habe für das [Kontrollierbarkeit-Vorsorgeprinzip](#headingTwo) argumentiert -- auszuzeichnen. 

Unter Akzeptanz der von mir verteidigten Vorsorgeprinzipien sollte die Menschheit die **Treibhausgaskonzentration auf das vorindustrielle Niveau (von max. 350ppm $CO_2$) so schnell wie möglich zurückführen**. 

Diese These habe ich in Pissarskoi ([2014]() und [2018]()) verteidigt. 


:::

## Sozial-ökologische Transformationspolitik

:::{.panel-tabset}

### Klimaanapassung

In den folgenden Forschungsvorhaben habe ich dazu beigetragen, 

* ökonomische Bewertungen von Klimaanpassungsmaßnahmen in Deutschland zu erstellen ([econCCadapt](http://www.oekonomie-klimawandel.de/))
* Visionen einer klimaresilienten Gesellschaft zu erarbeiten und politische Strategien zu ihrer Realisierung zu eruieren (Deutschland im Klimawandel

```{=html}
<div class="accordion" id="accordionExample">
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingOne">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
        <strong>econCCadapt: Ökonomie der Anpassung an den Klimawandel</strong>
      </button>
    </h2>
    <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample" style="">
      <div class="accordion-body">
        In diesem <a href="https://www.ioew.de/projekt/oekonomie_der_anpassung_an_den_klimawandel_integration_oekonomischer_modellierungen_und_institution/">Verbundvorhaben</a> wurde 
        <ul>
          <li>ein bestehendes ökonometrisches Modell (<a href="https://gws-os.com/de/energie-klima/modelle/detail/panta-rhei">Panta Rhei von GWS</a>) erweitert und kalibriert, um Szenarien mit Klimawandelfolgen für Deutschland berechnen zu können,</li>
          <li>ein regionales Input-Output-Modell für die Bewertung von Klimawandelkosten entwickelt sowie</li> 
          <li>institutionenökonomische Analysen von Klimaanpassungspolitiken durchgeführt.</li> 
        </ul>
        Darüber hinaus waren wir an der Begleitforschung beteiligt, in der Ergebnisse aus parallell stattfindenden Forschungsvorhaben zu Ökonomie des Klimawandels in Deutschland zusammengeführt und kommuniziert wurden. 
        Mein Anliegen in diesem Projekt lag darin, ökonomische Bewertungen von Kosten und Nutzen, die gewöhnlich auf der normativen Theorie des Präferenz-Utilitarismus basieren, um weitere normative Theorien zu erweitern, insbesondere um Bewertungen auf der Grundlage von Grundbefähigungen (capabilities). Hierbei bin ich über das Stadium von Skizzen und Diskussionspapieren nicht hinausgekommen. 

        Zu den folgenden Publikationen habe ich hingegen beigetragen:

        <ul>
          <li><a href="https://www.fona.de/medien/pdf/Hintergrundpapier_Forum_Kosten.pdf?m=1548322391&">Hirschfeld et al. 2015a: Kosten des Klimawandels und der Anpassung an den Klimawandel aus vier Perspektiven</a>: Policy Paper, das die Erkenntnisse aus Forschungsprojekten des BMBF-Programms "Ökonomie des Klimawandels" zusammenführt, die Kosten des Klimawandels abgeschätzt haben.</li>
          <li><a href="https://www.oekologisches-wirtschaften.de/index.php/oew/article/view/1400/1376">Hirschfeld et al. 2015b: Ökonomie des Klimawandels. Einführung in das Schwerpunktthema</a>: Wir haben einen Schwerpunkt in der Zeitschrift Ökologisches Wirtschaften herausgegeben, in dem die innerhalb von econCCadapt verfolgten Ansätze präsentiert wurden.</li>
          <li><a href="http://www.oekonomie-klimawandel.de/data/oekl/user_upload/Dateien/KNA_Hitze_Koeln_VorgehenErgebnisse_final.pdf">Pissarskoi et al. 2015: Abschätzung von Kosten und Nutzen der Anpassung an Hitzeereignisse</a>: dieser Arbeitsbericht fasst die Ergebnisse unserer Arbeiten zu einer normativ mehrdimensionalen Bewertung von Anpassungsmaßnahmen an Hitze in einer deutschen Großstadt. 
        </ul>
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingTwo">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
        <strong>Deutschland im Klimawandel: Anpassungskapazität und Wege in eine klimarobuste Gesellschaft 2050</strong>
      </button>
    </h2>
    <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample" style="">
      <div class="accordion-body">
        Dieses <a href="https://www.umweltbundesamt.de/themen/klima-energie/klimafolgen-anpassung/werkzeuge-der-anpassung/projektkatalog/deutschland-im-klimawandel-anpassungskapazitaet">Forschungsvorhaben im Auftrag des Umweltbundesamtes</a> hat 
        <ol>
          <li>die Struktur der deutschen Anpassungspolitik analysiert und bewertet</li>
          <li>Visionen einer klimaresilienten Gesellschaft und Transformationspfade dorthin in einem transdisziplinären Prozess erarbeitet. </li>
        </ol>
        Ich habe die Erstellung der Visionen klilaresilienter Gesellschaft in einer transdisziplinären Workshopreihe inhaltlich koordiniert. 
      
        Die Ergebnisse sind dokumentiert in:
        <ul>
          <li><a href="https://www.umweltbundesamt.de/sites/default/files/medien/656/dokumente/ioew_dik_endb_finale_fassung.pdf.pdf">Rupp et al. 2015: Deutschland im Klimawandel</a>: Endbericht des Vorhabens. Kapitel 4 stellt die Ergebnisse der Visionsbildung und die erarbeiteten Transformationspfade dar.</li>
          <li><a href="https://doi.org/10.14512/OEW300218">Rupp und Pissarskoi 2015: Klimaanpassung im Stadtquartier</a>: In diesem Aufsatz erläutern wir, wie eine transormative (im Gegensatz zu einer bewahrenden) Anpassungspolitik in Städten und urbanen Räumen ausgestaltet werden könnte.</li>
        </ul>
      </div>
    </div>
  </div>
</div>
```

### Energiesysteme
Dekarbonisierung der Energieversorgung in Deutschland erfordert eine umfangreiche Transformation des Energiesystems. Gesellschaftliche Konflikte bei der Realisierung dieser Transformation resultieren zum einen aus einer Uneinigkeit über die Ziele, die ein dekarbonisiertes Energieversorgungssystem leisten soll, und zum anderen aus hohen Unsicherheiten über die verfügbaren Technologieoptionen, ihre zukünftige Preisentwicklung, den Aufwand für ihre Realisierung etc. 

Im Rahmen von den folgenden Forschungsvorhaben habe ich Wertkonflikte bei der Transformation des Energiesystems analysiert:

- [LOBSTER](https://www.itas.kit.edu/projekte_betz10_lobster.php): Forschungsgruppe „Limits and Objectivity of Scientific Foreknowledge: The Case of Energy Outlooks” (LOBSTER)
- [Resystra](http://www.resystra.de/): Analyse der Zielanforderdungen an ein dekarbonisiertes Energieversorgungssystem und der Konflikte zwischen den Zielen.

```{=html}
<div class="accordion" id="accordionExample">
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingOne">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
        <strong>Pissarskoi (2016): Die Bürde des Möglichen</strong>
      </button>
    </h2>
    <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample" style="">
      <div class="accordion-body">
        Im Rahmen von InnoSmart habe ich Argumente rekonstruiert, in denen Vor- und Nachteile aus einer flächendeckenden Einführung von Smart Grids abgewogen werden. Diese Argumentanalysen haben ergeben, dass eine Beurteilung dieser Technologie wesentlich davon abhängt,
        <ul>
          <li> zu welchen Kostenersparnissen für das Energiesystem die Einführung von Smart Grids führen wird </li>
          <li> welche Datenschutzrisiken genau nicht vermieden werden können. </li>
        </ul>
        Eine gesellschaftliche Auseinandersetzung über die Einführung dieser Technologie würde von der Verfügbarkeit dieser Informationen signifikant profitieren. 

        Die Argumentanalyse ist dokumentiert  
        <ul>
          <li>ausführlich in <a href="https://nextclouds.webo.hosting/s/XCTM98dRmiXgJXR">Abschnitt 5 des Arbeitsberichtes (Konrad et al. 2017)</a></li>
          <li>in einer Zusammenfassung in <a href="https://publica-rest.fraunhofer.de/server/api/core/bitstreams/5d8d05b0-ad27-489b-8363-4e59231764c2/content">Kapitel 4.6 des Schlussberichts des Projektes (Mohaupt et al. 2016)</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingTwo">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
        <strong>Resilienz des Energiesystems: Analyse der Kontroverse über die Visionen (Wachsmuth et al. 2015)</strong>
      </button>
    </h2>
    <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample" style="">
      <div class="accordion-body">
        Im Rahmen des Projektes <a href="http://www.resystra.de/">Resystra</a> habe ich Argumente rekonstruiert, mit denen Zielvorstellungen eines zukünftigen Energiesystems in Deutschland begründet werden. Zwei Visionen haben sich als kontroverse Extreme gezeigt: ein zentrales Großversorgungssystem versus ein dezentrales Selbstversorgunssystem. 
        Die Argumentanalyse hat dabei ergeben:
        <ul>
        <li>Die beiden Visionen beinhalten unterschiedliche Anforderungen, die ein Energiesystem erfüllen soll.</li>
        <li> Es herrscht Uneinigkeit darüber, in welchem Maße die jeweiligen Visionen des Energiesystems ihre Anforderungen realisieren können.</li>
       </ul>
       Hieraus lassen sich Empfehlungen dazu ableiten, wie eine konstruktive gesellschaftliche Debatte über ein zukünftiges Energiesystem gestaltet werden sollte:
        <ul>
          <li>Anforderungen an ein Energiesystem sollten in einer gesellschaftlichen Deliberation beurteilt und gemäß demokratischen Verfahren festgelegt werden.</li>
          <li>Die identifizierten empirischen Unsicherheiten sollten nach Möglichkeit durch entsprechende empirische Forschung beseitigt werden.</li>
       </ul>
       Die Argumentanalyse ist dokumentiert worden in <a href="">Wachsmuth et al. 2015, Kapitel 5.3</a>
      </div>
    </div>
  </div>
</div>
```
### Ressourcen
Nach welchen Kriterien sollte beurteilt werden, ob eine Nutzung von natürlichen Ressourcen gerecht oder ungerecht ist? -- in den folgenden Aufsätzen mache ich Vorschläge dazu.

```{=html}
<div class="accordion" id="accordionExample">
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingOne">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
        <strong>Pissarskoi 2016: Ressourcen</strong>
      </button>
    </h2>
    <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample" style="">
      <div class="accordion-body">
        <a href="https://rdcu.be/d0nGf">Der Lexikonsbeitrag</a> gibt einen Überblick über normative Prinzipien und die sie begründenden normativen Theorien, die in der philosophischen Literatur diskutiert werden, um Ansprüche auf Zugang und Nutzung natürlicher Ressourcen zu begründen.
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingTwo">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
        <strong>Pissarskoi 2022: Doppelt ungerecht: Verteilung natürlicher Ressourcen</strong>
      </button>
    </h2>
    <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample" style="">
      <div class="accordion-body">
        In <a href="https://www.oekom.de/ausgabe/zukunftsfaehige-chemie-80924">diesem Aufsatz</a> begründe ich, warum die gegenwärtige Nutzung von natürlichen Rohstoffen in Deutschland ungerecht ist. Zwei Gründe bringe ich vor: 
        <ul>
          <li><strong>ungerechte Aneignung</strong>: die aktuelle international akzeptierte Praxis der Aneignung und des Handels von natürlichen Ressourcen ist nicht vernünftig rechtfertigbar</li>
          <li><strong>Übertragung von Risiken auf zukünftige Generationen</strong>: durch die Nutzung von nicht-erneuerbaren Rohstoffen verringern wir die verbleibenden Bestände für die zukünftigen Generationen. Da wir nicht ausschließen können, dass zukünftige Generationen auf diese Bestände angewiesen sein werden, ist es ungerecht, sie für Zwecke zu verwenden, auf die wir nicht angewiesen sind. 
        </ul>
      </div>
    </div>
  </div>
</div>
```

### Ernährung

```{=html}
<div class="accordion" id="accordionExample">
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingOne">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
        <strong>Kiesselbach and Pissarskoi 2023: Lowering the Consumption of Animal Products without Sacrificing Consumer Freedom</strong>
      </button>
    </h2>
    <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample" style="">
      <div class="accordion-body">
        In <a href="https://doi.org/10.1080/21550085.2021.1961201">diesem Aufsatz</a> unterbreiten und verteidigen wir einen pragmatischen Politikvorschlag, um Fleischkonsum signifikant zu reduzieren, und von dem wir glauben, dass er öffentlich akzeptiert werden dürfte. Es enthält zwei Instrumente:   
        <ol>
          <li>Regulierung, die bewirkt, dass Nutztiere nur artgerecht gehalten werden dürfen;</li>
          <li>Bedingungsloses Grundeinkommen in einer Höhe, die es erlaubt, das durchschnittliche Niveau an Fleischkonsum trotz der durch die tierethische Regulierung stark angestiegener Preise (gemäß (i)) aufrechtzuerhalten.</li>
        </ol>
        Eine nicht-akademische Darstellung der Idee haben Wir
        <ul>
          <li> <a href="https://medium.com/@matthias.kiesselbach/meat-backlash-94290f6eec8f">auf medium.com auf Englisch</a></li>
          <li> <a href="https://www.nd-aktuell.de/artikel/1157244.grundeinkommen-weniger-fleisch-mehr-geld.html">auf nd-aktuell.de auf Deutsch</a> veröffentlicht.
        </ul>
      </div>
    </div>
  </div>
</div>
```


### Umwelt- und Naturschutz

```{=html}
<div class="accordion" id="accordionExample">
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingOne">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
        <strong>Gerechtigkeit in der Umwelt- und Naturschutzpolitik</strong>
      </button>
    </h2>
    <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample" style="">
      <div class="accordion-body">
        <ul>
          <li><a href="https://www.umweltbundesamt.de/sites/default/files/medien/378/publikationen/texte_94_2015_umwelt-_und_naturschutzpolitik_als_gesellschaftspolitik_0.pdf">Schäfer et al. 2015: Umwelt- und Naturschutzpolitik -- Konzepte und zukünftige Herausforderungen</a>: Dieser Bericht enthält Empfehlungen, wie Gerechtigkeitsbelange in der Umwelt- und Naturschutzpolitik erkannt und kommuniziert werden sollten.</li>
          <li><a href="https://oekologisches-wirtschaften.de/index.php/oew/article/view/1101">Neuhäuser und Pissarskoi 2011: Umweltgerechtigkeit -- Von der Verantwortung in Politik und Unternehmen</a>: der Anlass dieses Schwerpunktes in Ökologisches Wirtschaften war die Beobachtung, dass Auseinandersetzungen über Gerechtigkeit in der Umwelt- und Klimapolitik kaum stattfinden, obwohl alle verfügbaren poltiischen Handlungsoptionen unterschiedliche Gerechtigkeitsprinzipien anstreben. Die Aufsätze in dem Schwerpunkt diskutieren einzelne Gerechtigkeitsaspekte. </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingTwo">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
        <strong>Pissarskoi 2018: Hat Natur Eigenwert? Und wenn ja: liefert das gute Gründe für den Naturschutz?</strong>
      </button>
    </h2>
    <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample" style="">
      <div class="accordion-body">
        In diesem Aufsatz (erschienen in den <a href="https://www.loccum.de/publikationen/9783817281176/">Loccumer Protokollen</a>) argumentiere ich dafür, dass es nicht zielführend ist, Anliegen der Naturschutzpolitik durch Verweise auf den Eigenwert der Natur zu begründen. Mein Gedankengang geht folgendermaßen:
        <ul>
          <li>es ist nicht schwer zu begrünen (und dürfte unkontrovers sein), dass alles, was lebendig ist, prima facie wertvoll und schützenswert ist.</li>
          <li>Es gibt aber sehr viele Arten des Lebendingen. Und neben dem Lebendigen gibt es aber viele weitere Belange, die prima facie wertvoll und schützenswert sind.</li>
          <li> Politische Handlungsentscheidungen müssen alle diesen normativ berücksichtigungswürdigen Belange berücksichtigen und zwischen ihnen abwägen. Die Prinzipien für eine Abwägung, bei der alle berücksichtigungswürdigen lebendigen Entitäten angemessen berücksichtigt werden, zu finden und transparent zu kommunizieren, ist eine relevantere, wenn auch anspruchsvollere Aufgabe für die Naturschutzpolitik.</li>  
        </ul>
      </div>
    </div>
  </div>
</div>
```
:::

## Technikfolgenbewertung

::: {.panel-tabset}
### Online Social Networks

Im Rahmen des Projektes [TWON](https://www.twon-project.eu/) werden digitale Twins von online sozialen Netzwerken (wie Facebook, Twitter/X, TikTok etc.) entwickelt. Das Ziel ist, die digitalen Twins dazu zu nutzen, um die Algorithmen der sozialen Netzwerke besser analysieren zu können. Verfügbarkeit von digitalen Twins von online sozialen Netzwerken birgt allerdings auch eigene Gefahren. 

Um ein besseres Verständnis über die Chancen und Risiken von der neu entstehenden Technologie zu verschaffen und Governance-Optionen für diese Technologie zu identifizieren, habe ich in Kooperation mit den Entwickler\*innen eine Ethik-Analyse erstellt.

Die wesentlichen Ergebnisse sind im [Policy Brief](https://www.twon-project.eu/?p=3508) zusammengefasst.

```{=html}
<div class="accordion" id="accordionExample">
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingOne">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
        <strong>Pissarskoi and Maes (2024): Twin of Online Social Networks – Impact Assessment and Ethical Guidance Handbook</strong>
      </button>
    </h2>
    <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample" style="">
      <div class="accordion-body">
        In <a href="https://ec.europa.eu/research/participants/documents/downloadPublic?
documentIds=080166e50a9b9303&appId=PPGMS">diesem Bericht</a>
        <ul>
          <li>unterscheiden wir vier Wege, wie digitale Twins von online sozialen Netzwerken -- wir nennen sie TWONs -- reguliert werden können: von freiem Zugang zu TWONs auf dem einen Extrem bis zur Nutzung von TWONs nur auf Gerichtsbeschluss auf dem anderen;</li>
          <li>rekonstruieren Argumente, die für und gegen alle vier Regulierungsweisen vorgebracht werden können;</li>
          <li>unsere Analyse der Argumente zeigt, dass keine Regulierungsweise überzeugend begründet, aber auch keine Regulierungsweise überzeugend zurückgewiesen werden kann. Denn alle Argumente setzen Prämissen ein, die entweder sehr unsicher sind oder ethisch kontrovers.</li>
          <li>hieraus leiten wir Empfelungen ab, was erforscht werden müsste und welche ethischen Festlegungen gesellschaftlich diskutiert werden sollten, damit eine begründete Entscheidung über die Nutzung von TWONs getroffen werden kann.</li>
        </ul>
        Kurzzusammenfassung der zentralen Aussagen unseres Berichts findet sich im <a href="https://www.twon-project.eu/?p=3508">Policy Brief</a>
      </div>
    </div>
  </div>
</div>
``` 


### Smart Grids


```{=html}
<div class="accordion" id="accordionExample">
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingOne">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
        <strong>Vor- und Nachteile von Smart Grids: Mohaupt et al. (2016) und Konrad et al. (2016)</strong>
      </button>
    </h2>
    <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample" style="">
      <div class="accordion-body">
        Im Rahmen von InnoSmart habe ich Argumente rekonstruiert, in denen Vor- und Nachteile aus einer flächendeckenden Einführung von Smart Grids abgewogen werden. Diese Argumentanalysen haben ergeben, dass eine Beurteilung dieser Technologie wesentlich davon abhängt,
        <ul>
          <li> zu welchen Kostenersparnissen für das Energiesystem die Einführung von Smart Grids führen wird </li>
          <li> welche Datenschutzrisiken genau nicht vermieden werden können. </li>
        </ul>
        Eine gesellschaftliche Auseinandersetzung über die Einführung dieser Technologie würde von der Verfügbarkeit dieser Informationen signifikant profitieren. 

        Die Argumentanalyse ist dokumentiert  
        <ul>
          <li>ausführlich in <a href="https://nextclouds.webo.hosting/s/XCTM98dRmiXgJXR">Abschnitt 5 des Arbeitsberichtes (Konrad et al. 2017</a></li>
          <li>in einer Zusammenfassung in <a href="https://publica-rest.fraunhofer.de/server/api/core/bitstreams/5d8d05b0-ad27-489b-8363-4e59231764c2/content">Kapitel 4.6 des Schlussberichts des Projektes (Mohaupt et al. 2016)</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>
```


### Converging Technologies

In einigen Forschungsvorhaben habe ich daran mitgewirkt zu analysieren, welchen Beitrag neu entstehende Technologien auf die Ziele Nachhaltiger Entwicklung haben können.

```{=html}
<div class="accordion" id="accordionExample">
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingOne">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
        <strong>Potenziale und Trends der Bionik</strong>
      </button>
    </h2>
    <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample" style="">
      <div class="accordion-body">
        Was charakterisiert Forschung zu Bionik bzw. Biomimetik und wie sieht die Forschungslandschaft in Deutschland aus? -- diesen Fragen sind wir im Forschungsvorhaben "Potentiale und Trends der Bionik" nachgegangen. Hierbei haben wir
        <ul>
          <li> drei Entwicklungsstränge der Bionik zu unterscheiden: Bionik als Funktionsmorphologie, Bionik als Biokyberlnetik (Robotik und Künstliche Intelligenz) sowie Nanobionik. Insbesondere die letzten beiden Stränge bilden einen Teil der Entstehung von so genannten "Converging Technologies", einer Verschmelzung von Datenverarbeitenden Technologien, Kognitionswissenschaften, Robotik, Bio- und Gentechnik und Nanotechnologien. </li>
          <li> eine empirische Bestandsaufnahme der deutschen Forschungslandschaft erstellt</li>
          <li> Treiber und Hemmnisse der bionischen Innovationen identifiziert.</li>
        </ul>
        Der Projektbericht ist erschienen  
        <ul>
          <li>auf Deutsch <a href="https://www.ioew.de/fileadmin/user_upload/DOKUMENTE/Publikationen/2007/Bionik_Aktuelle_Trends_und_zuk%C3%BCnftige_Potenziale.pdf">Bionik. Aktuelle Trends und zukünftige Potenziale</a></li>
          <li>auf Englisch als Sammelband bei Springer<a href="https://link.springer.com/book/10.1007/978-3-642-05246-0">Potentials and Trends in Biomimetics</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingTwo">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
        <strong>Selbstorganisierende adaptive Systeme</strong>
      </button>
    </h2>
    <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample" style="">
      <div class="accordion-body">
        Im Rahmen <a href="https://www.ioew.de/projekt/Selbstorganisierende_adaptive_Systeme/">dieses Projektes</a> wurde versucht, eine begründete Einschätzung zu marktlichen Potentialen, gesellschaftlichen Risiken und rechtlichen Hemmnissen von aus der Wissenschaft getriebenen Forschungsansätzen unter dem Namen "Organic Computing". 
      </div>
    </div>
  </div>
</div>
```

:::



