---
title: Über mich
---

::: {.callout-note collapse="true" appearance="minimal"}

## Biographische Motivation, nachträglich rationalisiert

Ich habe bereits eine gesellschaftliche Transformation miterlebt: Perestrojka -- Transformation der in der Sowjetunion etablierten politisch-ökonomischen Institutionen zu einer, so die Vision, freiheitlich-demokratischen Gesellschaftsordnung. Diese Vision ist bislang nicht realisiert worden^[mit Ausnahme der drei baltischen Länder, die als erste die Sowjetunion verlassen hatten]. 

* Die Perestrojka in der Sowjetunion verfolgte ein vollkommen berechtigtes Ziel: ein in vielen Hinsichten ungerechtes Institutionengefüge der Sowjetunion, das in sehr viele Lebensbereiche der Menschen eingriff und das einen im Durchschnitt relativ zu westeuropäischen Ländern geringen materiellen Wohlstand generierte, derart zu transformieren, dass zumindest die offensichtlichen Missstände beseitigt werden. 
* Die Umsetzung der Perestrojka führte jedoch nicht zum angestrebten Ziel, sondern zu einem nicht-intendierten Insititutionengefüge in den ehemaligen Sowjetrepubliken, mit vielen fatalen Konsequenzen.

Die frühzeitig industrialisierten Länder wie Deutschland befinden sich heute ebenfalls in einer Situation, in der eine umfassende Transformation geboten ist: 

* Es ist nicht sinnvoll bestreitbar, dass die Lebens- und Wirtschaftsweise der früh industrialisierten und heute relativ wohlhabenden Volkswirtschaften -- daunter auch Deutschland -- ungerecht gegenüber zukünftigen Generationen sowie vielen Menschen in den Ländern des Globalen Südens ist. 
  * Eindringliche Indizien für die Ungerechtigkeiten sind:
    * Der [Verbrauch nicht-erneuerbarer Ressourcen](https://www.resourcepanel.org/global-material-flows-database); 
    * die [Menge von Treibhausgasen](https://www.umweltbundesamt.de/daten/klima/treibhausgas-emissionen-in-deutschland#emissionsentwicklung), die jährlich emittiert werden; 
    * Geschwindigkeit, mit der die Artenvielfalt sinkt (Stand des Wissens wird dokumentiert in Berichten des [International Panels on Biodiversity and Ecosystem Services](https://www.ipbes.net/), [hier](https://zenodo.org/records/3553579/files/ipbes_global_assessment_report_summary_for_policymakers.pdf?download=1) ist die Summary des Berichtes von 2019).
    * Generellen Überblick bieten die Indikatoren:
      * [Planetary Boundaries](https://www.stockholmresilience.org/research/planetary-boundaries.html)
      * [Planetary Health Check](https://www.planetaryhealthcheck.org) 
  * Diese Indikatoren belegen nicht unmittelbar die Ungerechtigkeitsbehauptung. Es bedarf noch einer Begründung, warum diese Zahlenangaben intergenerationell und global ungerecht sind. Details dieser Begründung sind diffizil, ich habe in mehreren Publikationen mich bemüht, sie zu klären^[beispielsweise: ]. Der Grundgedanke der Begründung ist der folgende:
    * Das Ausmaß, in dem die heute lebende Menschheit Flächen nutzt, Rohstoffe abbaut und durch Verarbeitung von Ressourcen Emissionen freisetzt, gefährdet das Wohlergehen der zukünftigen Generationen. Die heutige Menschheit ist gleichwohl in der Lage, das Ausmaß der Eingriffe in ökologische Systeme derart zu reduzieren, dass die Gefährdung des Wohlergehens der zukünftigen Generationen unterlassen wird, ohne ihr eigenes Wohlergehen dadurch zu gefährden. 
    * Frühzeitig industrialisierte Länder tragen überproportional viel zum Ausmaß, in dem die Menschheit in die ökologischen Systeme eingreift. Es ist nicht ernsthaft wünschenswert, dass alle Menschen weltweit die Möglichkeit haben, in die ökologischen Systeme in dem Ausmaß einzugreifen, in dem ein\*e durchschnittliche\*r Bewohner\*in in den früh industrialisierten Ländern eingreift. 
  
* Aus diesem Grund ist es erforderlich, die Lebens- und Wirtschaftsweise in einem Land wie Deutschland so zu verändern, dass die Nutzung ökologischer Systeme im Durchschnitt in einem Ausmaß erfolgt, der sicherstellt, dass auch bei einer weltweiten Nutzung natürlicher Systeme in diesem Umfang künftige Generationen nicht gefährdet werden. 
  * Das bedeutet, dass die Ressourcenmenge, die in frühindustrialisierten Ländern, in einer Zeitperiode verbraucht wird^[man spricht hier vom Ressourcendurchsatz: Menge von Rohstoffen und eingesetzter Energie, die zur Produktion von Gütern und Erbringung von Dienstleistungen benötigt werden.], drastisch reduziert wird. 

Mich treibt nun die Frage um: Wie kann es nun vermieden werden, dass die westeuropäischen Gesellschaften angesichts des Erfordernisses einer Transformation die Erfahrung der Sowjetunion -- erst verschleppen, dann, wenn die negativen Auswirkungen des bestehenden Systems sich deutlich bemerkbar machen, eine Ruckartige, von oben durchgesetzte radikale Reformpolitik einsetzen -- wiederholen? 
:::

```{=html}
<div class="card border-info mb-3" style="width: 100%; max-width: 100%;">
  <div class="card-header">aktuell</div>
  <div class="card-body">
    <h5 class="card-title">Berater und Trainer für Argumentation und konstruktives Debattieren (freiberuflich)</h4>
    <p class="card-text">
      <ul>
        <li><a href="https://argumentationsagentur.de" class="card-link">ArgumentationsAgentur</a></li>
        <li><a href="https://forum-streitkultur.de/" class="card-link">Forum für Streitkultur</a></li>
      </ul>
    </p>
  </div>
</div>
```

::::: {.columns}
::: {.column width="58%"}
```{=html}
<!--
<div class="card text-white bg-primary">
  <h3 class="card-header">Beschäftigungen</h3>
</div>-->
<div class="card">
  <h3 class="card-header">Beschäftigungen</h3>
    <div class="card-body">
      <h5 class="card-title">Karlsruher Institut für Technologie, Institut für Technikzukünfte</h5>
      <h6 class="card-subtitle mb-2 text-muted">2023-2024</h6>
      <ul>
        <li>Wissenschaftlicher Mitarbeiter, Department für Soziologie, Forschungsprojekt <a href="https://www.twon-project.eu/" class="card-link">Twin of Online Social Network (TWON)</a></li>
      </ul>
    </div>
</div>

<div class="card">
  <div class="card-body">
    <h5 class="card-title">Universität Tübingen, Internationales Zentrum für Ethik in den Wissenschaften (IZEW)</h5>
    <h6 class="card-subtitle mb-2 text-muted">2017-2023</h6>
    <ul>
      <li>Wissenschaftlicher Mitarbeiter, Arbeitsbereiche <a href="https://uni-tuebingen.de/de/265260" class="card-link">Ethik und Bildung</a> sowie <a href="https://uni-tuebingen.de/de/21553">Natur und Nachhaltige Entwicklung</a> <span class="text-body-secondary">(2017-2019)</span></li> 
      <li>Leitung Verbundprojekt <a href="https://uni-tuebingen.de/en/166338" class="card-link">BATATA - Whose Bioeconomy? Tracing Visions of Socio-ecological Transformation and their Ethical Deliberation in Tanzania</a>, 
      Arbeitsbereich <a href="https://uni-tuebingen.de/de/21553">Natur und Nachhaltige Entwicklung</a> <span class="text-body-secondary">(2019-2023)</span></li>
    </ul>
  </div>
</div>
  
<div class="card">
  <div class="card-body">
    <h5 class="card-title">Institut für ökologische Wirtschaftsforschung GmbH, gemeinnützig (IÖW), Berlin</h5>
    <h6 class="card-subtitle mb-2 text-muted">2003-2017</h6>
    <ul>
      <li>Studentischer Mitarbeiter <span class="text-body-secondary">(2003-2010)</span> </li> 
      <li>Fellow  <span class="text-body-secondary">(2007-2010)</span> </li>
      <li>Wissenschaftlicher Mitarbeiter, Forschungsfeld <a href="https://www.ioew.de/das-ioew/organisation/forschungsfelder/umweltoekonomie-und-umweltpolitik" class="card-link">Umweltökonomie und Umweltpolitik</a> <span class="text-body-secondary">(2010-2017)</span></li>
    </ul>
  </div>
</div>

<div class="card">
    <div class="card-body">
    <h5 class="card-title">Karlsruher Institut für Technlogie, Institut für Philosophie</h5>
    <h6 class="card-subtitle mb-2 text-muted">2011</h6>
    <ul>
      <li>Wissenschaftlicher Mitarbeiter, Forschungsgruppe <a href="https://www.itas.kit.edu/projekte_betz10_lobster.php" class="card-link">Limits and Objectivity of Scientific Foreknowledge: The Case of Energy Outlooks” (LOBSTER)</a></li>
    </ul>
  </div>
</div>





<!--
<div class="card mb-3">
  <h3 class="card-header">Beschäftigungen</h3>
  <div class="card-body">
    <h5 class="card-title">Karlsruher Institut für Technlogie, Institut für Philosophie</h5>
    <h6 class="card-subtitle mb-2 text-muted">2011</h6>
    <ul>
      Wissenschaftlicher Mitarbeiter, Forschungsgruppe <a href="https://www.itas.kit.edu/projekte_betz10_lobster.php" class="card-link">Limits and Objectivity of Scientific Foreknowledge: The Case of Energy Outlooks” (LOBSTER)</a>
    </ul>
  </div>
  <div class="card-body">
    <h5 class="card-title">Institut für ökologische Wirtschaftsforschung GmbH, gemeinnützig (IÖW), Berlin </h5>
    <h6 class="card-subtitle mb-2 text-muted">2003-2017</h6>
    <ul>
      Studentischer Mitarbeiter (2003-2010) <br> Fellow (2007-2010) <br>
      Wissenschaftlicher Mitarbeiter, Forschungsfeld <a href="https://www.ioew.de/das-ioew/organisation/forschungsfelder/umweltoekonomie-und-umweltpolitik" class="card-link">Umweltökonomie und Umweltpolitik</a> (2010-2017)
    </ul>
  </div>
  <div class="card-body">
    <h5 class="card-title">Universität Tübingen, Internationales Zentrum für Ethik in den Wissenschaften (IZEW)</h5>
    <h6 class="card-subtitle mb-2 text-muted">2017-2023</h6>
    <ul>
      Wissenschaftlicher Mitarbeiter, Arbeitsbereiche <a href="https://uni-tuebingen.de/de/265260" class="card-link">Ethik und Bildung</a> sowie <a href="https://uni-tuebingen.de/de/21553">Natur und Nachhaltige Entwicklung</a> (2017-2019)<br> 
      Leitung Verbundprojekt <a href="https://uni-tuebingen.de/en/166338" class="card-link">BATATA - Whose Bioeconomy? Tracing Visions of Socio-ecological Transformation and their Ethical Deliberation in Tanzania</a>, 
      Arbeitsbereich <a href="https://uni-tuebingen.de/de/21553">Natur und Nachhaltige Entwicklung</a> (2019-2023)
    </ul>
  </div>
   <div class="card-body">
    <h5 class="card-title">Karlsruher Institut für Technologie, Institut für Technikzukünfte</h5>
    <h6 class="card-subtitle mb-2 text-muted">2023-2024</h6>
    <ul>
      Wissenschaftlicher Mitarbeiter, Department für Soziologie, Forschungsprojekt <a href="https://www.twon-project.eu/" class="card-link">Twin of Online Social Network (TWON)</a>
    </ul>
  </div>
</div>
-->
```
:::
::: {.column width="2%"}
:::
::: {.column width="40%"}
```{=html}
<div class="card">
  <h3 class="card-header">Qualifikationen</h3>
  <div class="card-body">
    <h5 class="card-title">Promotion in Philosophie zu Dr.phil.</h5>
    <h6 class="card-subtitle mb-2 text-muted">2007-2012</h6>
    <ul>
     <li>Freie Universität Berlin, Institut für Philosophie <span class="text-body-secondary">(2007-2012)</span></li>
     <li>Förderung durch die <a href="https://www.boeckler.de/de/faust-detail.htm?sync_id=HBS-005850" class="card-link">Hans-Böckler-Stiftung</a> <span class="text-body-secondary">(2007-2010)</span></li>
    </ul>
    
  </div>
</div>
<div class="card">
  <div class="card-body">
    <h5 class="card-title">Philosophie und Volkswirtschaftslehre, Magister Artium</h5>
    <h6 class="card-subtitle mb-2 text-muted">2000-2006</h6>
    <ul>
     <li>Universität Leipzig <span class="text-body-secondary">(2000-2001: ein Semester in Mathematik, Logik und Wissenschaftstheorie)</span></li>
     <li>Universität Mannheim <span class="text-body-secondary">(2001-2003: Grundstudium)</span></li>
     <li>Freie Universität Berlin <span class="text-body-secondary">(2003-2006: Hauptstudium)</span></li>
    </ul>
  </div>
</div>
<div class="card">
  <h3 class="card-header">Allgemeinbildung</h3>
  <div class="card-body">
    <h5 class="card-title">Abitur</h5>
    <h6 class="card-subtitle mb-2 text-muted">1999</h6>
    <ul>
     <li>Theodor-Heuss Gymnasium, Wolfenbüttel <span class="text-body-secondary">(1993-1999)</span></li>
     <li>Hauptschule Wallstraße, Wolfenbüttel <span class="text-body-secondary">(1993)</span></li>
     <li>Mittelschule Nr. 37, Bischkek (bis 1991: Frunse), Kirgisistan (bis 1991: Kirgisische SSR) <span class="text-body-secondary">(1986-1992)</span></li>
    </ul>
  </div>
</div>
<div class="card">
  <h3 class="card-header">Zivildienst</h3>
  <div class="card-body">
    <h5 class="card-title">Lebenshilfe Braunschweig</h5>
    <h6 class="card-subtitle mb-2 text-muted">1999-2000</h6>
    <ul>
     <li>Betreuer in einem Wohnheim für kognitiv beeinträchtigte Personen</li>
    </ul>
  </div>
</div>
<!--
<div class="card mb-3">
  <h3 class="card-header">Qualifikationen</h3>
  <div class="card-body">
    <h5 class="card-title">Philosophie und Volkswirtschaftslehre</h5>
    <h6 class="card-subtitle mb-2 text-muted">Magister Artium</h6>
    <ul>
      Universität Mannheim (2001-2003: Grundstudium)<br>
      Freie Universität Berlin (2003-2006: Hauptstudium)
    </ul>
  </div>
  <div class="card-body">
    <h5 class="card-title">Promotion in Philosophie</h5>
    <h6 class="card-subtitle text-muted">Dr. phil.</h6>
    <ul>
      Freie Universität Berlin, Institut für Philosophie (2007-2012)<br>
      Förderung durch die <a href="https://www.boeckler.de/de/faust-detail.htm?sync_id=HBS-005850" class="card-link">Hans-Böckler-Stiftung</a>
    </ul>
  </div>
</div>
-->
```
:::
:::::